### ISSUE TITLE
AAVE V3 QA (Avalanche, Optimism, Arbitrum, Harmony, Polygon, Fantom) Schema Version 2.0.1  Subgraph Version  1.0.2  Methodology Version 1.0.0

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#579] opened 2022-07-14 16:43 UTC
<google-sheets-html-origin><style type="text/css"></style>

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v3-avalanche&tab=protocol |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Date Reviewed | 7-Jul-22 |   |   |   |   |  
Schema Version | 1.3.0 |   |   |   |   |  
Subgraph Version | 1.0.0 |   |   |   |   |  
Methodology Version | 1.0.0 |   |   |   |   |  
  |   |   |   |   |   |  
Protocol |   |   |   |   |   |  
Section | Value | Status |   | Comments |   |  
usageMetricsDailySnapshots | dailyTransactionCount | NOT OK | Public data | Subgraph data is more than the snowtrace data. either multiplier or something else. Sourncing data: https://snowtrace.io/txs?a=0x794a61358D6845594F94dc1DB02A252b5b4814aD&ps=100&p=7 |   |  
usageMetricsDailySnapshots | dailyDepositCount | NOT OK | Public data | Subgraph data is more than the snowtrace data. either multiplier or something else. Sourncing data: https://snowtrace.io/txs?a=0x794a61358D6845594F94dc1DB02A252b5b4814aD&ps=100&p=7 |   |  
usageMetricsDailySnapshots | dailyWithdrawCount | NOT OK | Public data | Subgraph data is more than the snowtrace data. either multiplier or something else. Sourncing data: https://snowtrace.io/txs?a=0x794a61358D6845594F94dc1DB02A252b5b4814aD&ps=100&p=7 |   |  
usageMetricsDailySnapshots | dailyBorrowCount | NOT OK | Public data | Subgraph data is more than the snowtrace data. either multiplier or something else. Sourncing data: https://snowtrace.io/txs?a=0x794a61358D6845594F94dc1DB02A252b5b4814aD&ps=100&p=7 |   |  
usageMetricsDailySnapshots | dailyRepayCount | NOT OK | Public data | Subgraph data is more than the snowtrace data. either multiplier or something else. Sourncing data: https://snowtrace.io/txs?a=0x794a61358D6845594F94dc1DB02A252b5b4814aD&ps=100&p=7 |   |  
  |   |   |   |   |   |  
Pool Overview |   |   |   |   |   |  
Rewards |   | not ok | Public data | In the rewards column, the first data (of lending rewards are in line with official data), but the second data (of borrowing rewards) are less than those in the official website, about half. Probably using rewards deviding the deposit balance and not the borrowing balance. |   |  
  |   |   |   |   |   |  
Pool |   |   |   |   |   |  
vault schema | rates: [InterestRate!]! | not ok | Public data | Interest rates are slightly different from APY presented in the official websites (more than the compounding from APR to APY). Is this out of date? double check. |   |  
  |   |   |   |   |   |  
Event |   |   |   |   |   |  
Liquidate |   | unsure | Dune | No liquidation data showing. Data not available on snowtrace, so this option may not be indexed in this subgraph. |   |

**Comment by spitko** [comment] 2022-07-15 12:24
Snowtrace transaction list only shows direct contract function calls, and does not include any contract-to-contract calls, for example borrows through [WETH Gateway](https://snowtrace.io/tx/0xe478786dfc6dcdc8a716933aba64123f48a152eec578ec044f5d96ba8c8ff553). A better way would be to look at [events](https://snowtrace.io/address/0x794a61358d6845594f94dc1db02a252b5b4814ad#events) and filter by topic0, for example borrow event topic0 is `0xb3d084820fb1a9decffb176436bd02558d15fac9b0ddfed8c465bc7359d7dce0`.

The reward APY calculation is done by the dashboard and not included in the subgraph code. The issue is that Aave has separate stable/variable borrow balances and rewards, and the calculation is using the total borrow balance, which is incorrect in this case.

Interest rates are indeed currently in APR and not APY, will fix this.
Liquidation data does exist and is indexed, will investigate why the dashboard is not showing this. Can be seen on Snowtrace events filtering by topic0: `0xe413a321e8681d831f4dbccbca790d2952b56f977908e45be37335533e005286`.

**Comment by ishraq8** [comment] 2022-07-15 13:48
Thank you for this, you are correct, filtering by event aligns the snowtrace with the data I am seeing output on subgraph. Made a note to use this on other AAVE v3 deployments. Appreciate the explanation.

**Comment by this-username-is-taken** [comment] 2022-07-22 11:12
@ishraq8 this is ready for another round

**Comment by ishraq8** [comment] 2022-07-22 11:52
on it!

**Comment by ishraq8** [comment] 2022-08-11 18:15
@spitko @this-username-is-taken 
This subgraph looks great on all chains except for two issues with rewards on Avalanche and Optimism below:

**Optimism**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v3-optimism&tab=poolOverview
-- | --
Date Reviewed | 11-Aug-22
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0


Pool Overview |   |   |   |  
-- | -- | -- | -- | --
Rewards |   | not ok | Public data | Rewards column, OP is 0. Liquidity mining rewards recently launched. 


**Avalanche**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v3-avalanche&tab=protocol
-- | --
Date Reviewed | 11-Aug-22
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0


Pool Overview |   |   |   |  
-- | -- | -- | -- | --
Rewards |   | not ok | Public data | Rewards column, WAVAX percentage is higher on supply side and lower on borrow side on the subgraph compared to APR. Website shows APR. Is this a front end issue? The prior front end was changed.

**Comment by jaimehgb** [comment] 2022-08-22 23:14
`Rewards column, OP is 0. Liquidity mining rewards recently launched.`

Rewards are accounted for in OP. But its USD price is 0 because AAVE oracle doesn't have data for OP. Our price-lib doesn't still support Optimism ... Here there are 3 options:
- Attempt to add Optimism support to our price-lib
- Provisionally hardcode some DEX with the highest liquidity for OP at the current time
- Leave it as is for now

@this-username-is-taken, option 1 seems like the most correct, but it is so small of an issue (in my opinion) and will probably take some time to implement that we might get away with option 2 for the time being?

**Comment by this-username-is-taken** [comment] 2022-08-23 01:07
@jaimehgb agreed. For pricing of just 1 or 2 (reward) tokens, it's fine just use some DEX pricing instead of the price lib. We do that for some of the compound forks too.

**Comment by ishraq8** [comment] 2022-08-23 01:11
Ignore the avalanche issue, it is a front end and the subgraph is accurate. 

The front end calculation is: `(emissions/borrowed or supply)*100*356`. The front end is dividing `borrowed emission/supply` and `supply emissions/borrowed`. Why the APR is wonky. I just manually calculated and the accurate matching is correct.

**Comment by jaimehgb** [comment] 2022-08-26 19:19
@ishraq8 the fixes for optimism rewards are on their way 🚀 

Since it will probably resync from scratch[ I've grafted this version ](https://api.thegraph.com/subgraphs/name/jaimehgb/aave-v3)from a recent block. It won't have the rewards on the past snapshots but they should appear in the most recent ones, in case you want to QA it.

**Comment by ishraq8** [comment] 2022-08-26 20:56
Sweet thanks @jaimehgb! Have a great weekend. 🚀

**Comment by ishraq8** [comment] 2022-08-27 02:51
The OP you grafted is accurate. the front end is still flipping the borrowed and supply numbers, but the raw data is accurate (note for future front end deployment). These issues are resolved.

**Comment by MichaelC1999** [comment] 2022-08-29 14:02
> The OP you grafted is accurate. the front end is still flipping the borrowed and supply numbers, but the raw data is accurate (note for future front end deployment). These issues are resolved.

I believe the subgraph should reorder the reward tokens array or the emissions arrays to line up with each other. The way that we link a reward emissions amount to a specific reward token/type is by its index within the field array (rewardTokens[1] corresponds to rewardTokenEmissionsAmount[1]). The emissions fields dont have any sort of indication about which token, whether it is a lending reward emission or borrowing etc, so the array ordering is the only way to link emissions to the reward type.

**Comment by jaimehgb** [comment] 2022-08-29 17:48
Ahh, I see what you mean.
Yeah, that is wrong at the subgraph level then.

Should be fixed with: https://github.com/messari/subgraphs/pull/897
I deployed a version to see if it works [here](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3?version=pending&selected=logs). It is currently syncing. I'm re-opening the issue for now.

**Comment by ishraq8** [comment] 2022-08-29 18:55
> Ahh, I see what you mean.
> 
> Yeah, that is wrong at the subgraph level then.
> 
> 
> 
> Should be fixed with: https://github.com/messari/subgraphs/pull/897
> 
> I deployed a version to see if it works [here](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3?version=pending&selected=logs). It is currently syncing. I'm re-opening the issue for now.

@jaimehgb Pull 897 will fix it on avax aave v3 too correct? Similar issue there which I incorrectly assumed was front end.

**Comment by jaimehgb** [comment] 2022-08-29 19:01
@ishraq8 yes, it should 🚀 
It should be happening on all the networks actually. Maybe not in all pools, but some, since depends on chance 😅 

I'll deploy a new one for each network so we can graft into prod.

**Comment by this-username-is-taken** [comment] 2022-08-29 22:39
@jaimehgb I just approved https://github.com/messari/subgraphs/pull/897. Don't forget to graft these over once they've fully synced and QAed on staging

**Comment by jaimehgb** [comment] 2022-08-30 10:04
@ishraq8 
I've deployed the latest version on all networks, here:
- [AVAX](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-avax)
- [Optimism](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3?version=pending)
- [Arbitrum](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-arbitrum)
- [Harmony](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-harmony)
- [Polygon](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-polygon)
- [Fantom](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-fantom)

If you could confirm that rewards are properly calculated everywhere now :D 
Then I'll graft them into prod

**Comment by ishraq8** [comment] 2022-08-30 12:22
@jaimehgb 

![Image](https://user-images.githubusercontent.com/47088402/187435185-111a937b-222a-4d83-91fb-7af299a3b3e7.png)

Are the borrow and deposit `distributionend` suppose to be the same. Sorry for the confusion on my end. Only Avax and optimism currently have rewards.

**Comment by jaimehgb** [comment] 2022-08-30 15:41
> Only Avax and optimism currently have rewards.

Oh well 😅  I'll only deploy those then for now

> Are the borrow and deposit distributionend suppose to be the same

Not necessarily, but it is possible. Both reward tokens are created independently, triggered by different events, so it should be fine. The deposit `distributionEnd` matches with the one I can fetch from the contracts directly. For borrows, I wasn't able to retrieve it but I would expect it to be right.

**Comment by this-username-is-taken** [comment] 2022-09-01 01:31
will this not impact historical rewards?

**Comment by jaimehgb** [comment] 2022-09-01 11:00
> will this not impact historical rewards?

Yes, since these values are kept in the snapshots.

Optimism, Arbitrum, Harmony, Polygon and Fantom have been already synced from scratch and grafted into production (after @ishraq8 double checked).

The only missing now is [AVAX](https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-avax), which is taking longer to sync.

**Comment by ishraq8** [comment] 2022-09-02 13:42
@jaimehgb Avax synced and it matches perfectly to front end and historical data. Please go ahead and graft into prod. Appreciate all your efforts!

**Comment by this-username-is-taken** [comment] 2022-09-02 15:06
@jaimehgb gotcha, that sounds good!

**Comment by jaimehgb** [comment] 2022-09-02 16:00
Currently grafting: https://thegraph.com/hosted-service/subgraph/messari/aave-v3-avalanche?version=pending&selected=logs

I think we can close this issue then 🔥

**Closed by jaimehgb** 2022-09-02 16:00 UTC
Labels: data quality
