### ISSUE TITLE
AAVE V2 (Avalanche) Extended

### ISSUE THREAD

**Issue by jacubcub** [messari/subgraphs#704] opened 2022-08-01 19:31 UTC
There are accounts with borrow position balances but no lending position balances. Lending positions are there but they appear to be closed and have 0 balance.

For example this account: 0xc5ed2333f8a2c351fca35e5ebadb2a82f5d254c3
You can [use this query to see](https://api.thegraph.com/subgraphs/name/messari/aave-v2-avalanche-extended/graphql?query=query+accountHistoricalPositions+%7B%0A++accounts%28%0A++++where%3A+%7Bid%3A+%220xc5ed2333f8a2c351fca35e5ebadb2a82f5d254c3%22%7D%0A++%29+%7B%0A++++account_id%3A+id%0A++++positions%28where%3A+%7B%7D%29+%7B%0A++++++balance%0A++++++side%0A++++++market+%7B%0A++++++++market_id%3A+id%0A++++++++inputTokenPriceUSD%0A++++++++inputToken+%7B%0A++++++++++decimals%0A++++++++++symbol%0A++++++++%7D%0A++++++%7D%0A++++++hashOpened%0A++++++hashClosed%0A++++%7D%0A++%7D%0A%7D) 

This affects multiple accounts. You can see the top borrowers are showing larger outstanding borrow balances than the top lenders are showing for deposit balances in [this data app](https://jacubcub-lending-whales-data-app-lending-whales-ux3p7x.streamlitapp.com/)
![image](https://user-images.githubusercontent.com/40643172/182230150-df1419d1-6f37-4791-9421-aa67236f5919.png)

**Comment by dmelotik** [comment] 2022-09-06 03:53
Just seeing this issue now, as it got burried in our issues. I am linking this to #751 as it is also position related.

I think the issue is related to what I describe below. Basically the balances of borrows are reading deposits and it is throwing everything off.

Notes for me: I think `subtractPosition()` should get it's balanceResult from the debt tokens not the aToken balances.

**Comment by dmelotik** [comment] 2022-09-09 17:46
Another instance reported by borgley [API call](https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum/graphql?query=query+MyQuery+%7B%0A++account%28id%3A+%220x4093fbe60ab50ab79a5bd32fa2adec255372f80e%22%29+%7B%0A++++positions%28first%3A+100%29+%7B%0A++++++id%0A++++++balance%0A++++++side%0A++++++market+%7B%0A++++++++inputToken+%7B%0A++++++++++symbol%0A++++++++++decimals%0A++++++++%7D%0A++++++++inputTokenPriceUSD%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D)

**Comment by dmelotik** [comment] 2022-10-07 03:44
Partially fixed in #985 . But created a new issue #1082 in order track the new work on this.

**Closed by dmelotik** 2022-10-07 03:44 UTC
Labels: duplicate, data quality
