### ISSUE TITLE
PancakeSwap-V2-Swap BSC: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2400] opened 2023-10-12 14:43 UTC
Indexing errors on pancakeswap-v2-swap
bsc: 28431789 
Link: https://okgraph.xyz/?q=messari%2Fpancakeswap-v2-swap-bsc
```A determinstic fatal error occured at block 28431789: transaction 4a35667e07531a3697ccd6444c4b0de5c743d335428b1a9a5ce7ad555bc04b31: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0xa9f551de0f330654f37bcd89128d8828e4f820f000 to i32 wasm backtrace: 0: 0x3b06 - <unknown>!~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x41f0 - <unknown>!src/common/getters/getOrCreateToken 2: 0x4625 - <unknown>!src/common/creators/createLiquidityPool 3: 0x50ce - <unknown>!src/mappings/factory/handlePairCreated in handler `handlePairCreated` at block #28431789 (be1a18e7f9b6f7d1a14361f99de32ad0a0a8b3f7579b8b10d1fa077236d496a9)```

**Comment by melotik** [comment] 2023-11-08 21:53
<img width="858" alt="Screenshot 2023-11-08 at 2 52 13 PM" src="https://github.com/messari/subgraphs/assets/60583747/34c7e57a-a146-4607-aa1f-2559ca4f9751">
We have an error trying to graft at block `28431589` which is 180ish blocks behind the previous failed block

**Comment by melotik** [comment] 2024-02-15 17:45
Closing since this is a near duplicate of https://github.com/messari/subgraphs/issues/2483

**Closed by melotik** 2024-02-15 17:45 UTC
Labels: p0
