### ISSUE TITLE
curve-finance ethereum (PENDING): Protocol Error totalValueLockedUSD

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1928] opened 2023-03-23 06:23 UTC
Field: totalValueLockedUSD
Value: $1,091,765,898,076,262.60
Description: This field on dexAmmProtocol entity has a value below $0 or above $100,000,000,000.

**Comment by bye43** [comment] 2023-03-23 13:09
Dupe of: https://github.com/messari/subgraphs/issues/1927

**Closed by bye43** 2023-03-23 13:09 UTC
Labels: bug, monitor
