### ISSUE TITLE
#bug; rewardTokens / stakedOutputTokenAmount /  rewardTokenEmissionsUSD data quality issue in Trader Joe (Avalanche)

### ISSUE THREAD

**Issue by TKYAngus** [messari/subgraphs#1611] opened 2023-01-16 10:11 UTC
Link to subgraph: https://api.thegraph.com/subgraphs/name/messari/trader-joe-avalanche

`rewardTokens` is empty array (`[]`) for this Trader Joe V1 pool:
- 0xbb4646a764358ee93c2a9c4a147d5aded527ab73

`rewardTokenEmissionsUSD` is 0 for these Trader Joe V1 pools in hourly/daily snapshots:

- 0xa389f9430876455c36478deea9769b7ca4e3ddb1
- 0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256
- 0x87dee1cc9ffd464b79e058ba20387c1984aed86a
- 0x781655d802670bba3c89aebaaea59d3182fd755d
- 0x6f3a0c89f611ef5dc9d96650324ac633d02265d3
- 0xfe15c2695f1f920da45c30aae47d11de51007af9
- 0xd5a37dc5c9a396a03dd1136fc76a1a02b1c88ffa
- 0x2e02539203256c83c7a9f6fa6f8608a32a2b1ca2

`stakedOutputTokenAmount` is negative for these Trader Joe V1 pools:

- 0xf4003f4efbe8691b60249e6afbd307abe7758adb
- 0x2a8a315e82f85d1f0658c5d66a452bbdd9356783
- 0xf723feea2e376b7231cb250f7628fffc3f2dbd10

**Comment by bye43** [comment] 2023-01-17 15:57
Hey @TKYAngus thanks for the report! Right now, reward token metrics are on the backlog for certain DEXs. We are actually tracking this for trader joe here: https://github.com/messari/subgraphs/issues/1026.

**Comment by dmelotik** [comment] 2023-04-04 15:43
Closing this, as it is a duplicate of #1026

**Closed by dmelotik** 2023-04-04 15:43 UTC
Labels: bug, question, data quality
